srping:
  profiles:
    active:
    - dev
---
spring:
    profiles:dev
    application:
    name:microspringcloud-config-dev
---
spring:
    profiles:test
    application:
    name:microspringcloud-config-test
